# Generated by Django 5.1.3 on 2024-12-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Health', 'Health'), ('Education', 'Education'), ('Lifestyle', 'Lifestyle'), ('Business', 'Business')], default='Technology', max_length=50),
        ),
    ]
