# Generated by Django 5.1.3 on 2024-12-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Health', 'Health'), ('Education', 'Education'), ('Lifestyle', 'Lifestyle'), ('Business', 'Business'), ('Travel', 'Travel')], default='Technology', max_length=50),
        ),
    ]
